#!/bin/bash

if [ "$1" == "" ]; then
  echo "Must specify version number"
  exit 1
fi

docker build . -t skytapcmscripttools.azurecr.io/course_manual_manager:latest -t skytapcmscripttools.azurecr.io/course_manual_manager:$1
