#!/bin/bash

if [ "$1" == "" ]; then
  echo "Must specify version number"
  exit 1
fi

docker build . -t skytapcmscripttools.azurecr.io/script_publisher:latest -t skytapcmscripttools.azurecr.io/script_publisher:$1
