# frozen_string_literal: true

source "https://rubygems.org"
ruby ">= 3.1.0"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", "~> 7.0.4"
gem "httplog", "~> 1.6.2"
gem "rest-client", "~> 2.0.2"
gem "rubyzip", "~> 2.3"
