build:
  name: Build
  image_name: ruby:3.2-bullseye
  command: ["/bin/bash", "-c", "bundle install && bundle config deployment true && bundle package"]
  persistent_artifacts:
    - Gemfile.lock
run:
  name: Run
  image_name: ruby:3.2-bullseye
  command: ["/bin/bash", "-c", "bundle config deployment true && bundle exec ruby script.rb"]
  env:
    - "RUBYLIB=./lib"