#!/usr/bin/env bash

# Copyright 2023 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

[ -z "$DOCKER" ] && DOCKER=$(which docker || which podman || true)
[ -z "$DOCKER" ] && echo "docker or podman is required" && exit 1

IMAGE_NAME_LINE=$(cat config.yml|grep ^image_name || true)
IMAGE_NAME=$(echo ${IMAGE_NAME_LINE#*:}|xargs || true)
[ -z "$IMAGE_NAME" ] && echo "Image name not found in config.yml" && exit 1

BUILD_IMAGE_NAME_LINE=$(cat config.yml|grep ^build_image_name || true)
BUILD_IMAGE_NAME=$(echo ${BUILD_IMAGE_NAME_LINE#*:}|xargs || true)
[ -z "$BUILD_IMAGE_NAME" ] && BUILD_IMAGE_NAME=$IMAGE_NAME

COMMAND_LINE=$(cat config.yml|grep ^command || true)
COMMAND=$(echo ${COMMAND_LINE#*:}|xargs || true)

ARGS_LINE=$(cat config.yml|grep ^args || true)
ARGS=$(echo ${ARGS_LINE#*:}|xargs || true)
