#!/usr/bin/env bash

# Copyright 2022 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PUBLISHER_IMAGE_NAME=ghcr.io/mhgoldman/cm_script_publisher:0.1

DOCKER=$(which podman || which docker)
[ -n "$DOCKER" ] || (echo "docker or podman is required" && exit 1)

pushd $(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/.. > /dev/null

[ -f utils/build ] && utils/build

$DOCKER run -v $PWD:/work -w /work $PUBLISHER_IMAGE_NAME

popd > /dev/null