#!/usr/bin/env bash

# Copyright 2022 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pushd $(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/.. > /dev/null

source utils/init

#TODO redudant bc already doing it as part of package
[ -f utils/build ] && utils/build

utils/package

SCRIPT_NAME="${PWD##*/}"

SCRATCH_DIR=$PWD/.scratch

[ -e $SCRATCH_DIR ] && rm -rf $SCRATCH_DIR
mkdir -p $SCRATCH_DIR

cp $PWD/utils/_push $SCRATCH_DIR
cp $PWD/push.yml $SCRATCH_DIR
cp $PWD/out/$SCRIPT_NAME.zip $SCRATCH_DIR

$DOCKER run  --rm -v $SCRATCH_DIR:$SCRATCH_DIR -w $SCRATCH_DIR $UTILS_IMAGE_NAME bash _push

popd > /dev/null