executor:
  base: ruby:3.3-bullseye
  customizer: build/customizer
  root: /build
  src:
    - build/**/*
    - Gemfile*
  persistent_artifacts:
    "Gemfile.lock": "/build/Gemfile.lock"
script:
  command:
    - "/bin/bash"
    - "-c"
    - "bundle exec ruby script.rb"
  root: /script
  src:
    - lib/**/*
    - script.rb
    - Gemfile*
  env:
    - "RUBYLIB=./lib"