# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "faker"
gem "ruby-terraform", "~> 1.7"
gem "fileutils"
gem "httplog"
gem "faker"
gem "sshkey"
