{}
# build:
  # image: debian:bookworm
  # command:
  #   - "/bin/bash"
  #   - "-c"
  #   - "echo"
  # context:
  #   - "Gemfile"
  #   - "lib/**/*"
  # devArtifacts:
  #   "package-lock.json": "/build/package-lock.json"
  # artifacts:
  #    "package-lock.json": "/build/package-lock.json"
  #    "node_modules": "/build/node_modules"
  # workDir: "/build"
# src:
#   - lib/**/*
#   - script.sh