image: node:22-bookworm
command:
  - "/bin/bash"
  - "-c"
  - "npm config set update-notifier false && npm start --silent"
# egress: true
env:
  - "NODE_PATH=./lib:./script/node_modules"
# workDir: "/script"