#!/bin/bash

# Copyright 2022 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pushd $(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/.. > /dev/null

DOCKER=$(which podman || which docker)
[ -n "$DOCKER" ] || (echo "docker or podman is required" && exit 1)

IMAGE_NAME_LINE=$(cat config.yml|grep image_name)
IMAGE_NAME=$(echo ${IMAGE_NAME_LINE#*:}|xargs)

[ -f Gemfile.lock ] && rm -f Gemfile.lock
[ -d vendor/cache ] && rm -rf vendor/cache

echo -e "Building Ruby dependencies...\n"

$DOCKER run  --rm -v $PWD:/tmp/course_script -w /tmp/course_script $IMAGE_NAME /bin/bash -c bundle package

echo -e "Build complete\n"

popd > /dev/null