#!/bin/bash

# Copyright 2022 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DOCKER=$(which podman || which docker)
[ -n "$DOCKER" ] || (echo "docker or podman is required" && exit 1)

IMAGE_NAME_LINE=$(cat config.yml|grep image_name)
IMAGE_NAME=$(echo ${IMAGE_NAME_LINE#*:}|xargs)

COMMAND_LINE=$(cat config.yml|grep command)
COMMAND=$(echo ${COMMAND_LINE#*:}|xargs)

ARGS_LINE=$(cat config.yml|grep args)
ARGS=$(echo ${ARGS_LINE#*:}|xargs)