#!/bin/bash

# Copyright 2022 Skytap Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
OUTPUT_DIR=out
OUTPUT_NAME="${PWD##*/}".zip
ZIP_IMAGE_NAME=alpine:3.17.0

pushd $(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/.. > /dev/null

source utils/init

utils/build

$DOCKER run  --rm -v $PWD:/tmp/course_script -w /tmp/course_script $ZIP_IMAGE_NAME apk add zip && mkdir -p $OUTPUT_DIR && zip -r $OUTPUT_DIR/$OUTPUT_NAME * -x $OUTPUT_DIR/\* -x utils/\* -x lib/stub_data/\*

echo Zip package written to $OUTPUT_DIR/$OUTPUT_NAME

popd > /dev/null